version: '3.8'

services:
  fastapi:
    build:
      context: ./mini_groq_project
      dockerfile: dockerfile
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    expose:
      - "5000"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
